### ISSUE TITLE
GetBucketACL returns Grantee without DisplayName

### ISSUE THREAD

**Issue by evgeniiz321** [nspcc-dev/neofs-s3-gw#854] opened 2023-10-17 03:58 UTC
E.g.:

```
{'ResponseMetadata': 
{'RequestId': 'b8dcaa51-b559-4bf1-8205-2e89e67f7e7b', 'HostId': '', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amz-request-id': 'b8dcaa51-b559-4bf1-8205-2e89e67f7e7b', 'date': 'Tue, 17 Oct 2023 03:45:24 GMT', 'content-length': '580', 'content-type': 'text/xml; charset=utf-8'}, 'MaxAttemptsReached': True, 'RetryAttempts': 0
}, 
'Owner': {'DisplayName': 'NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM', 'ID': 'NbUgTSFvPmsRxmGeWpuuGeJUoRoi6PErcM'}, 
'Grants': [
{'Grantee': {'DisplayName': '', 'EmailAddress': '', 'ID': '031a6c6fbbdf02ca351745fa86b9ba5a9452d785ac4f7fc2b7548ca2a46c4fcf4a', 'Type': 'CanonicalUser', 'URI': ''}, 'Permission': 'FULL_CONTROL'}
]
}
```

Grantee inner structure is always without DisplayName, need to check other empty values for grantee as well.

**Comment by smallhive** [comment] 2023-10-27 08:10
I consider this was fixed in another commit because the correct master version gives the next result:

```shell
$ export BUCKET=heh$(date +%s); aws s3api create-bucket --bucket $BUCKET --endpoint http://localhost:19080 --acl public-
$ aws --no-paginate s3api get-bucket-acl --bucket $BUCKET --endpoint http://localhost:19080
{
    "Owner": {
        "DisplayName": "Ng5NAi19ebpPBPawocd9xSBBMPMLARfGHX",
        "ID": "Ng5NAi19ebpPBPawocd9xSBBMPMLARfGHX"
    },
    "Grants": [
        {
            "Grantee": {
                "Type": "Group",
                "URI": "http://acs.amazonaws.com/groups/global/AllUsers"
            },
            "Permission": "READ"
        },
        {
            "Grantee": {
                "DisplayName": "Ng5NAi19ebpPBPawocd9xSBBMPMLARfGHX",
                "ID": "02c87c26eb1a6af2b64ac1e714578b9cd4a3a3adcdffd1a6c3d2cb03faaf4f1293",
                "Type": "CanonicalUser"
            },
            "Permission": "FULL_CONTROL"
        }
    ]
}
```
I see the example response has a different format, and if your case still have an empty display name, please add the steps to reproduce. @evgeniiz321

**Comment by evgeniiz321** [comment] 2023-11-02 02:01
This is fixed now, feel free to close this one

**Closed** 2023-11-02 04:20 UTC
Labels: bug
