### ISSUE TITLE
Deleted bucket is returned from list-buckets method

### ISSUE THREAD

**Issue by vdomnich-yadro** [nspcc-dev/neofs-s3-gw#695] opened 2022-08-30 17:49 UTC
The issue can be reproduced by running test [test_s3_buckets ](https://github.com/nspcc-dev/neofs-testcases/blob/892b8f227a137f3e671c4ed9b1e1e647c04db4c7/pytest_tests/testsuites/services/test_s3_gate.py#L83).

The issue reproduces against devenv (happens about 1 time per 8-10 runs of the test).
I couldn't reproduce it against the cloud env.

## Steps of the test (highlights)
Referenced log: [test-log.txt](https://github.com/nspcc-dev/neofs-s3-gw/files/9455366/test-log.txt)

1. Create 2 buckets
```
Related test log:
16:45:55 [INFO] Created S3 bucket 55a8ebbf-07cc-459b-9ef8-caa7225dbdf6:
16:46:02 [INFO] Created S3 bucket 18a271ee-f74d-45fc-9520-39b0c2f105ef
```
3. Wait until buckets are returned from the list-buckets method.
4. Put object in the 1st bucket.
5. Try to delete the 1st bucket - it expectedly fails.
6. Try to delete the 2nd bucket - s3 gateway replies that bucket was deleted:
```
Related test log:
16:46:09 [INFO] S3 Delete bucket result: {'ResponseMetadata': {'RequestId': '9c8d1df5-ec69-46a9-a39b-954eeb7e07de', 'HostId': '', 'HTTPStatusCode': 204, 'HTTPHeaders': {'x-amz-request-id': '9c8d1df5-ec69-46a9-a39b-954eeb7e07de', 'date': 'Tue, 30 Aug 2022 16:46:09 GMT'}, 'RetryAttempts': 0}}
```
7. Wait 5 seconds, then tick epoch.
8. Check whether containers of the buckets still exist in neofs (with `neofs-cli container list` and `neofs-cli container get` commands):
```
Related test log:
16:46:19 [INFO] Container BtHiHyEGFTofmFb5pahXvY1p57iySG3FJHTkfbYbfQ4w is in the list
16:46:19 [INFO] Container BtHiHyEGFTofmFb5pahXvY1p57iySG3FJHTkfbYbfQ4w was found
16:46:19 [INFO] Container 3N7TGiftp8uwRvVkf77Dda93zkrWqJo8WQ1XFZrFpGRf is in the list
16:46:20 [INFO] Container 3N7TGiftp8uwRvVkf77Dda93zkrWqJo8WQ1XFZrFpGRf was found
```
9. Call `head` on bucket - s3 gateway replies that bucket not found (as expected):
```
Related test log:
16:46:20 [INFO] S3 Head bucket error: An error occurred (404) when calling the HeadBucket operation: Not Found
```
11. Call `list-buckets` and check whether deleted bucket is in the list:
```
Related test log:
16:46:20 [DEBUG] Response body:
...many-buckets...<Bucket><Name>18a271ee-f74d-45fc-9520-39b0c2f105ef</Name><CreationDate>2022-08-30T16:46:00Z</CreationDate></Bucket>...many-buckets...
```

**Expected result:** the deleted bucket is not present in the list
**Actual result:** the deleted bucket is present in the list

## Version used:
```
<project path="morph-crest" revision="9b3e1acb071cf6fe35adcd99f4b1c71a13900b7f" upstream="master" />
  <project path="neo-go" revision="536303ef0a600fd9a6763a9da769b350f7af2ea0" upstream="mgmt-gethashbyid" />
  <project path="neo-preodolenie" revision="59838a401f1a9b696d660ac9985d911166ee4b37" upstream="master" />
  <project path="neofs-contract" revision="564f147ea1ada9582f9e91f430100ee3598d25e9" upstream="refs/tags/v0.15.4" />
  <project path="neofs-dev-env" revision="0afb18f5bc74f057ad2ae22b49325b274ac3dae1" upstream="internal_exp_b" />
  <project path="neofs-http-gw" revision="1c51979a03acc56ec6077cf187810c025fd3a3ee" upstream="master" />
  <project path="neofs-testcases/neofs-keywords" revision="98b7f2601e5cc4f67184d4321da56df5531b68d5" upstream="internal_tmp_b" />
  <project path="neofs-keywords" revision="58650099362f05b51b97f04e2244a4ba20f88351" upstream="master" />
  <project path="neofs-locode-db" revision="ffd8516fccb63c9955f1d4202fb8f5b858188aa1" upstream="refs/tags/v0.2.1" />
  <project path="neofs-node" revision="c7c1c257e1b0da0eafff9943f3297581817778f1" upstream="master" />
  <project path="neofs-s3-gw" revision="9590b3933388576a75ea55f570103633f68f235b" upstream="master" />
  <project path="neofs-testcases" revision="df598f7116d44f20dad661ca81cc129b99e3f360" upstream="internal_tmp_b" />  
```

## Neofs logs
[neofs-logs.zip](https://github.com/nspcc-dev/neofs-s3-gw/files/9455375/neofs-logs.zip)

**Comment by KirillovDenis** [comment] 2022-08-31 09:18
Could you provide s3-gw config?

It seems only `dns` resolving is enabled and badly configured. So after creating bucket we cannot find it and cannot delete (we return 204 since cannot find bucket and therefore don't have to delete anything).
s3 logs:
```
2022-08-30T16:46:20.194Z	debug	layer/layer.go:371	bucket not found	{"error": "failed resolve: couldn't resolve container '18a271ee-f74d-45fc-9520-39b0c2f105ef' as '18a271ee-f74d-45fc-9520-39b0c2f105ef.container': lookup 18a271ee-f74d-45fc-9520-39b0c2f105ef.container on 127.0.0.11:53: server misbehaving"}
2022-08-30T16:46:20.194Z	error	handler/util.go:25	could not get bucket info	{"request_id": "946c2dc6-a652-4d2c-afb0-4a4e0a1f686b", "method": "HeadBucket", "bucket_name": "18a271ee-f74d-45fc-9520-39b0c2f105ef", "object_name": "", "error": "NoSuchBucket: 404 => The specified bucket does not exist"}
2022-08-30T16:46:20.194Z	error	api/router.go:158	something went wrong	{"status": 404, "request_id": "946c2dc6-a652-4d2c-afb0-4a4e0a1f686b", "method": "HeadBucket", "description": "Not Found"}
```

**Comment by alexvanin** [comment] 2022-09-01 10:54
Can we try to reproduce it with `NEOFS_MORPH_DISABLE_CACHE=true` option in neofs-node?

**Comment by KirillovDenis** [comment] 2022-09-02 10:50
And check with [this node PR](https://github.com/nspcc-dev/neofs-node/issues/1632). Maybe it's related.

**Comment by alexvanin** [comment] 2022-09-15 10:41
> The issue reproduces against devenv (happens about 1 time per 8-10 runs of the test).

Is it reproduces now with the same frequency?

**Comment by dansingjulia** [comment] 2022-09-19 07:49
I checked it on v0.1.1-nb-20220916.1 40 times, it's not reproduce.

**Comment by alexvanin** [comment] 2022-09-19 08:33
> I checked it on v0.1.1-nb-20220916.1 40 times, it's not reproduce.

Closed.

**Closed by alexvanin** 2022-09-19 08:33 UTC
Labels: bug, yaczrokh, P2, 2022Q4
