### ISSUE TITLE
Sometimes created bucket is not available in list-buckets output

### ISSUE THREAD

**Issue by vdomnich-yadro** [nspcc-dev/neofs-s3-gw#628] opened 2022-07-27 06:41 UTC
## Steps to Reproduce (for bugs)
The issue is intermittent and does not occur on every run. I am observing it in 1 out of 3 tries.

The issue can be reproduced both with AWS CLI and with boto3 client. Steps are:
* Create a new S3 bucket
* Create another S3 bucket
* List buckets
* Check whether the created buckets are present in the list

## Expected Behavior
The response from list-buckets contains both created buckets.

## Current Behavior
In about 30% of cases the response from list-buckets does not contain one or both of the created buckets.

However, if I keep trying listing buckets, then after 3-15 seconds I am getting list of buckets that includes my bucket. See attached [log](https://github.com/nspcc-dev/neofs-s3-gw/files/9195733/boto3.log).
Some comments to what is happening in the log:
```
18:13:16 - Created bucket e83eb1f1-80da-4302-8996-8d958369b9f0
18:13:21 - Created bucket 2e1247e2-53cf-497e-9363-65864ba8db9d
18:13:28 - call list-buckets
           response does not contain any of the buckets e83eb1f1-80da-4302-8996-8d958369b9f0 or 2e1247e2-53cf-497e-9363-65864ba8db9d
18:13:33 - call list-buckets again
           same result - response does not contain the buckets e83eb1f1-80da-4302-8996-8d958369b9f0 or 2e1247e2-53cf-497e-9363-65864ba8db9d
18:13:39 - call list-buckets again
           finally we see both buckets in list-buckets response

Interestingly, creation timestamps are 18:13:14 and 18:13:21 respectively:
  <Bucket>
    <Name>e83eb1f1-80da-4302-8996-8d958369b9f0</Name>
    <CreationDate>2022-07-26T18:13:14Z</CreationDate>
  </Bucket>
  <Bucket>
    <Name>2e1247e2-53cf-497e-9363-65864ba8db9d</Name>
    <CreationDate>2022-07-26T18:13:21Z</CreationDate>
  </Bucket>
```

## Your Environment
Dev-env with s3 gateway configured with multiple peers and tree service.

* Version used:
```
NEO-GO         - 0.99.1-pre-197-g68b5260f
NEOFS-CLI      - v0.30.0
NEOFS-AUTHMATE - v0.22.0
AWS            - 2.2.0
```

* Server setup and configuration:
```
  <project name="morph-crest.git"     revision="a915cb945b7571c6098a21185bba620f7e0516eb" />
  <project name="neo-go.git"          revision="68b5260fb5ed953fae6237dae781ba8baa4451da" />
  <project name="neo-preodolenie.git" revision="a6fb56b26392cf837940483d09dcc6db272d9427" upstream="master" />
  <project name="neofs-contract.git"  revision="fbc63cf0543209dcbb19414011df423f462a6d9e" upstream="refs/tags/v0.15.3" />
  <project name="neofs-dev-env.git"   revision="25648ff629eae3c028dd9dc9d1391fb2021331eb" upstream="internal_exp_b"    />
  <project name="neofs-http-gw.git"   revision="98991d63ae7ede4f51d0c2c51310e0cc37791356" upstream="refs/tags/v0.22.0" />
  <project name="neofs-locode-db.git" revision="ffd8516fccb63c9955f1d4202fb8f5b858188aa1" upstream="refs/tags/v0.2.1"  />
  <project name="neofs-node.git"      revision="2a1c5557f271828d9388db4de65d859f2fddb63f" upstream="refs/tags/v0.30.0" />
  <project name="neofs-s3-gw.git"     revision="618025c969deb61aba91d4c4074defd382e4daeb" upstream="refs/tags/v0.22.0" />
  ```

**Comment by KirillovDenis** [comment] 2022-07-27 07:02
@vdomnich-yadro Could you also provide the `neofs-s3-gw` logs?

**Comment by KirillovDenis** [comment] 2022-07-27 09:15
I reproduced this with the following config:
```yaml
# ...
default_policy: "REP 2"

peers:
  0:
    priority: 1
    address: s01.neofs.devenv:8080
    weight: 1
  1:
    priority: 1
    address: s02.neofs.devenv:8080
    weight: 1
  2:
    priority: 1
    address: s03.neofs.devenv:8080
    weight: 1
  3:
    priority: 1
    address: s04.neofs.devenv:8080
    weight: 1
# ...
```
Looks like the problem is not with `neofs-s3-gw`.
Sometimes we:
* Can't list newly created container from other node (successful PUT on `s04` but empty list (there is one old system auth box container) on `s03`):

**aws cli**:
```shell
$ aws s3 ls 
2022-07-27 10:53:00 

$ aws s3api create-bucket --bucket b-1658911704

$ aws s3 ls
2022-07-27 10:53:00 
```

**s3 logs**: 
```
2022-07-27T11:48:24.897+0300    info    api/router.go:167       call method     {"status": 200, "request_id": "7abba6a9-ad6a-4cb0-a749-1ef35d198b42", "method": "ListBuckets", "description": "OK"}
2022-07-27T11:48:25.598+0300    debug   layer/layer.go:352      bucket not found        {"error": "failed resolve: couldn't resolve container 'b-1658911704': NNS contract fault exception: at instruction 3437 (THROW): unhandled exception: \"token not found\""}
container put  s04.neofs.devenv:8080
container get  s04.neofs.devenv:8080
2022-07-27T11:48:27.650+0300    info    handler/put.go:671      bucket is created       {"container_id": "DqMtgNxm55bR7pa6ST54BDq7npmxDNHG27ubQzdQ6dzb"}
2022-07-27T11:48:27.650+0300    info    api/router.go:167       call method     {"status": 200, "request_id": "5346bcc0-a69f-49e4-90a3-7e93fc431317", "method": "CreateBucket", "description": "OK"}
container list  s03.neofs.devenv:8080
get from listing  DS4sbgSEuyRj7vZ53uMKXpsGXdo7p2pv6BivhPJXJhuC
container get  s03.neofs.devenv:8080
```
* See deleted container (removal `3Dr7Pay9eryVnfNqUbWccjaFA3opEsWGZUeakko75LVW` container on `s04` node but can list it in `s03` and get it on `s02`):

**aws cli**:
```shell
$ aws s3 ls 
2022-07-27 11:59:48 b-1658912387
2022-07-27 10:53:00 

$ aws s3api delete-bucket --bucket b-1658912387

$ aws s3 ls 
2022-07-27 11:59:48 b-1658912387
2022-07-27 10:53:00 
```
**s3 logs**: 
```
container list  s03.neofs.devenv:8080
get from listing  3Dr7Pay9eryVnfNqUbWccjaFA3opEsWGZUeakko75LVW
container get  s02.neofs.devenv:8080
b-1658912387
get from listing  DS4sbgSEuyRj7vZ53uMKXpsGXdo7p2pv6BivhPJXJhuC
container get  s04.neofs.devenv:8080

2022-07-27T11:59:51.328+0300    info    api/router.go:167       call method     {"status": 200, "request_id": "e7431d4d-3c0c-4430-8925-4860c7ed8ec3", "method": "ListBuckets", "description": "OK"}
container delete  s04.neofs.devenv:8080 
container get  s04.neofs.devenv:8080 
2022-07-27T11:59:53.083+0300    info    api/router.go:167       call method     {"status": 204, "request_id": "f1dc3fed-108b-41f9-b887-a6cdbc5b0585", "method": "DeleteBucket", "description": "No Content"}
container list  s03.neofs.devenv:8080
get from listing  3Dr7Pay9eryVnfNqUbWccjaFA3opEsWGZUeakko75LVW
container get  s02.neofs.devenv:8080
b-1658912387
get from listing  DS4sbgSEuyRj7vZ53uMKXpsGXdo7p2pv6BivhPJXJhuC
container get  s02.neofs.devenv:8080

2022-07-27T11:59:56.062+0300    info    api/router.go:167       call method     {"status": 200, "request_id": "ff132793-62d7-46d6-adf6-d5de3146b2aa", "method": "ListBuckets", "description": "OK"}
```

**Comment by vdomnich-yadro** [comment] 2022-07-27 09:51
Thank you @KirillovDenis ! I will work on providing logs for other issue [#610] then.

**Comment by vdomnich-yadro** [comment] 2022-07-27 09:52
@anatoly-bogatyrev, please, take a look at this issue - it is what we discussed on Tuesday.
Feel free to re-route it to a different component if it is not an s3 gateway problem.

**Comment by KirillovDenis** [comment] 2022-07-27 10:29
I suppose this task is blocked by https://github.com/nspcc-dev/neofs-node/issues/1632 now

**Comment by alexvanin** [comment] 2022-07-27 14:32
As the temporary solution, I can suggest to disable RPC cache on storage node. Uncomment this line in storage node config and restart environment: https://github.com/nspcc-dev/neofs-dev-env/blob/e904506e3d569c4190031826ab9e05350ff276a6/services/storage/.storage.env#L30

**Comment by KirillovDenis** [comment] 2022-09-08 06:32
@vdomnich-yadro  Is this bug reproduced after [PR](https://github.com/nspcc-dev/neofs-node/issues/1632) was merged?

**Comment by alexvanin** [comment] 2022-09-08 08:10
> As the temporary solution, I can suggest to disable RPC cache on storage node. Uncomment this line in storage node config and restart environment: https://github.com/nspcc-dev/neofs-dev-env/blob/e904506e3d569c4190031826ab9e05350ff276a6/services/storage/.storage.env#L30

Offtop: there is a new way to disable cache on neofs-node master branch. Now to disable cache set negative value of [morph.cache_ttl](https://github.com/nspcc-dev/neofs-node/blob/8e6e89aca323c43d277fbd56c9ea7535fd0d5260/config/example/node.yaml#L84).

```yaml
morph:
  cache_ttl: -1
```
```
NEOFS_MORPH_CACHE_TTL=-1
```

**Comment by alexvanin** [comment] 2022-09-22 10:20
@dansingjulia Can you also look at it?

**Comment by dansingjulia** [comment] 2022-10-07 14:19
looks like not reproduce

**Closed** 2022-10-07 14:57 UTC
Labels: bug, yaczrokh, P2, 2022Q4
