### ISSUE TITLE
OPTIONS request with CORS returns 500

### ISSUE THREAD

**Issue by evgeniiz321** [nspcc-dev/neofs-s3-gw#842] opened 2023-10-11 00:39 UTC
Following CORS rules:

```
    cors_config = {
        "CORSRules": [
            {
                "AllowedMethods": ["GET"],
                "AllowedOrigins": ["*"],
                "AllowedHeaders": ["x-amz-meta-header1"],
            },
            {
                "AllowedMethods": ["PUT"],
                "AllowedOrigins": ["http://www.example.com"],
                "AllowedHeaders": ["x-amz-meta-header2", "x-amz-meta-header3"],
            },
            {
                "AllowedMethods": ["DELETE"],
                "AllowedOrigins": ["http://www.example1.com"],
                "AllowedHeaders": [],
            },
            {
                "AllowedMethods": ["POST"],
                "AllowedOrigins": ["http://www.example2.com"],
                "AllowedHeaders": ["*"],
            },
        ]
    }
```

Try to perform OPTIONS request: 
```
method = 'OPTIONS', url = 'https://s3.neofs.devenv:8080/yournamehere-0lgnys1xy3qr5ykg-1'
headers = {'Access-Control-Request-Headers': 'x-amz-meta-header1', 'Access-Control-Request-Method': 'GET', 'Origin': 'http://any.origin'}
```

500 is returned:

```
2023-10-11T00:05:35.057Z	info	api/router.go:162	call method	{"status": 200, "host": "s3.neofs.devenv:8080", "request_id": "b3bfd622-f97d-4cfb-aa1f-248d0e2c937d", "method": "PutBucketCors", "bucket": "yournamehere-0lgnys1xy3qr5ykg-1", "object": "", "description": "OK"}
2023-10-11T00:05:38.076Z	debug	api/user_auth.go:30	couldn't receive access box for gate key, random key will be used
2023-10-11T00:05:38.085Z	error	handler/util.go:29	call method	{"status": 500, "request_id": "fcff94e5-218a-4cd5-9194-1c1e0dc79134", "method": "Options", "bucket": "yournamehere-0lgnys1xy3qr5ykg-1", "object": "", "description": "could not get cors", "error": "unmarshal cors: EOF"}
```

## Steps to Reproduce
1. See test_cors_header_option at s3tests_boto3/functional/test_s3_neofs.py

## Regression

I'm not sure if it ever worked, but due to s3 tests - it should.

Logs - [containers_logs.tar.gz](https://github.com/nspcc-dev/neofs-s3-gw/files/12863163/containers_logs.tar.gz)

**Comment by smallhive** [comment] 2023-10-31 09:55
The problem is the same like in #841 and will be fixed with merging #890

**Closed** 2023-11-08 16:06 UTC
Labels: bug, triage
