### ISSUE TITLE
Test S3: put object with ACL failed

### ISSUE THREAD

**Issue by vvarg229** [nspcc-dev/neofs-s3-gw#791] opened 2023-06-14 08:56 UTC
After the commit https://github.com/nspcc-dev/neofs-s3-gw/commit/7af8848be1721f3bb3fdc57117d5c36efbc9855c all tests except the  "Test S3: put object with ACL failed" tests pass.

These tests are falling down with an error:
```
acl_grants = [], permitted_users = 'AllUsers'

    def assert_s3_acl(acl_grants: list, permitted_users: str):
        if permitted_users == "AllUsers":
            grantees = {"AllUsers": 0, "CanonicalUser": 0}
            for acl_grant in acl_grants:
                if acl_grant.get("Grantee", {}).get("Type") == "Group":
                    uri = acl_grant.get("Grantee", {}).get("URI")
                    permission = acl_grant.get("Permission")
                    assert (uri, permission) == (
                        "http://acs.amazonaws.com/groups/global/AllUsers",
                        "FULL_CONTROL",
                    ), "All Groups should have FULL_CONTROL"
                    grantees["AllUsers"] += 1
                if acl_grant.get("Grantee", {}).get("Type") == "CanonicalUser":
                    permission = acl_grant.get("Permission")
                    assert permission == "FULL_CONTROL", "Canonical User should have FULL_CONTROL"
                    grantees["CanonicalUser"] += 1
>           assert grantees["AllUsers"] >= 1, "All Users should have FULL_CONTROL"
E           AssertionError: All Users should have FULL_CONTROL

pytest_tests/helpers/s3_helper.py:154: AssertionError
```
It seems that the access permissions are not given correctly.

Full allure report:
[S3_CHECK_master.zip](https://github.com/nspcc-dev/neofs-s3-gw/files/11743684/S3_CHECK_master.zip)
To view it, perform the steps below:

```
unzip S3_CHECK_master.zip
allure serve S3_CHECK_master
```

env:
```
neo-go 0.101.1
neofs-s3-authmate 0.27.0-5-g7af8848b (it's equal latest master https://github.com/nspcc-dev/neofs-s3-gw/tree/6f0ea5d34a17247fd3b5d7477b3d0297b1919903)
neofs-cli 0.36.1-15-gdbc59825-dirty
AWS aws-cli/2.9.19 
Python/3.11.2 Linux/6.2.0-20-generic source/x86_64.ubuntu.23 prompt/off
```

**Comment by roman-khimov** [comment] 2023-06-14 09:30
Did it ever work correctly? With 0.26.1, for example?

**Comment by vvarg229** [comment] 2023-06-14 10:07
> Did it ever work correctly? With 0.26.1, for example?

On version 0.26.1 these tests pass:
[S3_CHECK_0_26_1.zip](https://github.com/nspcc-dev/neofs-s3-gw/files/11744438/S3_CHECK_0_26_1.zip)
On version 0.27.0, these tests fail due to a bug that we fixed in https://github.com/nspcc-dev/neofs-testcases/issues/571 :
[S3_CHECK_0_27_0.zip](https://github.com/nspcc-dev/neofs-s3-gw/files/11744466/S3_CHECK_0_27_0.zip)

**Comment by roman-khimov** [comment] 2023-06-14 13:23
Looks like a #768 regression.

**Comment by roman-khimov** [comment] 2023-06-14 16:40
AWS CLI part of the test succeed, which suggests that the gateway is not completely broken. And for some reason this test stopped failing at me after an initial unsuccessful run:
```
$ pytest --alluredir my-allure-123 pytest_tests/testsuites/services/s3_gate/test_s3_object.py -k test_s3_put_object_acl
...
pytest_tests/testsuites/services/s3_gate/test_s3_object.py::TestS3GateObject::test_s3_put_object_acl[boto3-ENABLED] PASSED                                                                                                                                                                                                                                                            [ 75%]
pytest_tests/testsuites/services/s3_gate/test_s3_object.py::TestS3GateObject::test_s3_put_object_acl[boto3-SUSPENDED] PASSED                                                                                                                                                                                                                                                          [100%]
...
```

**Comment by vvarg229** [comment] 2023-06-14 18:18
> And for some reason this test stopped failing at me after an initial unsuccessful run:

@roman-khimov have you tried restarting dev-env?

**Comment by roman-khimov** [comment] 2023-06-14 19:43
Sure. I've even managed to get
```
pytest_tests/testsuites/services/s3_gate/test_s3_object.py::TestS3GateObject::test_s3_put_object_acl[boto3-ENABLED] PASSED                                                                                                                                                                                                                                                            [ 75%]
pytest_tests/testsuites/services/s3_gate/test_s3_object.py::TestS3GateObject::test_s3_put_object_acl[boto3-SUSPENDED] FAILED                                                                                                                                                                                                                                                          [100%]
pytest_tests/testsuites/services/s3_gate/test_s3_object.py::TestS3GateObject::test_s3_put_object_acl[boto3-SUSPENDED] ERROR                                                                                                                                                                                                                                                           [100%]
```
The other thing that bugs me is the other test prints `[ERROR] FULL_CONTROL is given to All Users` and doesn't fail at the same time. So I'd say some more effort needed to untangle this. At the same time I'd say it's not release-critical for now (AWS manages to work after all).

**Comment by smallhive** [comment] 2023-07-17 13:22
After deep debugging, I've found next:
* S3 works properly
* eACL sets and reads correctly, but with some notes

Let's see on the next part of the logs from S3 gate and IR node:
```
2023-07-17T03:30:12.361Z    s3  debug	layer/object.go:252	put object	{"reqId": "1b13b675-36de-47b1-94af-a0021e934906", "bucket": "22ecd326-1189-4777-a664-df977db6b8be", "cid": "B8QzYg9CxHQcN3Tmr7YnrELzNd4bJyoxbs2V3sNhWeQy", "object": "572ee614-83be-49f3-b14e-fe3b44405eb8", "oid": "262VzmpRy6E2B8UNTJjYaNVuefrPaQf5Cdddjwtd4qj9"}
2023-07-17T03:30:12.369Z    s3  warn	layer/container.go:162	SetContainerEACLTable	{"container": "B8QzYg9CxHQcN3Tmr7YnrELzNd4bJyoxbs2V3sNhWeQy"}
2023-07-17T03:30:12.378Z    ir	info	container/handlers.go:49	notification	{"type": "set EACL"}
2023-07-17T03:30:12.383Z    ir	debug	client/notary.go:483	notary request with prepared main TX invoked	{"tx_hash": "1140084473f669cb1af0433fe945034a5d9818cc497a341c62aa6df03fe02642", "valid_until_block": 500, "fallback_hash": "379bed4c8537b74adb7f63c7dbe913f1803177e19a569f4f34cef603aa81201d"}
2023-07-17T03:30:13.134Z    ir	debug	event/listener.go:362	notary parser not set	{"chain": "morph", "contract": "72576c968205e75eabc87708394839f1cf09cd57", "method": "setEACL"}
2023-07-17T03:30:13.134Z    ir	debug	innerring/innerring.go:236	new block	{"index": 388}
2023-07-17T03:30:13.382Z    s3  info	api/router.go:162	call method	{"status": 200, "host": "s3.neofs.devenv:8080", "request_id": "1b13b675-36de-47b1-94af-a0021e934906", "method": "PutObject", "bucket": "22ecd326-1189-4777-a664-df977db6b8be", "object": "572ee614-83be-49f3-b14e-fe3b44405eb8", "description": "OK"}
2023-07-17T03:30:13.389Z    s3  debug	layer/layer.go:499	get object	{"reqId": "ce2ea835-e919-4c97-8f93-695009de2ff2", "bucket": "22ecd326-1189-4777-a664-df977db6b8be", "cid": "B8QzYg9CxHQcN3Tmr7YnrELzNd4bJyoxbs2V3sNhWeQy", "object": "572ee614-83be-49f3-b14e-fe3b44405eb8", "oid": "262VzmpRy6E2B8UNTJjYaNVuefrPaQf5Cdddjwtd4qj9"}
2023-07-17T03:30:13.389Z    s3  warn	handler/acl.go:314	GetObjectACLHandler	{"encodeedObjectACL": {"Owner":{"ID":"NVbGSZ5WjhzwG8AGPkYqyXgm9yXvF915nH","DisplayName":"NVbGSZ5WjhzwG8AGPkYqyXgm9yXvF915nH"},"AccessControlList":null}}
2023-07-17T03:30:13.389Z    s3  warn	handler/acl.go:319	GetObjectACLHandler	{"================================= start =================================": {"Owner":{"ID":"NVbGSZ5WjhzwG8AGPkYqyXgm9yXvF915nH","DisplayName":"NVbGSZ5WjhzwG8AGPkYqyXgm9yXvF915nH"},"AccessControlList":null}}
2023-07-17T03:30:14.133Z    ir	debug	innerring/innerring.go:236	new block	{"index": 389}
2023-07-17T03:30:14.394Z    s3  debug	layer/layer.go:499	get object	{"reqId": "ce2ea835-e919-4c97-8f93-695009de2ff2", "bucket": "22ecd326-1189-4777-a664-df977db6b8be", "cid": "B8QzYg9CxHQcN3Tmr7YnrELzNd4bJyoxbs2V3sNhWeQy", "object": "572ee614-83be-49f3-b14e-fe3b44405eb8", "oid": "262VzmpRy6E2B8UNTJjYaNVuefrPaQf5Cdddjwtd4qj9"}
2023-07-17T03:30:14.394Z    s3  info	api/router.go:162	call method	{"status": 200, "host": "s3.neofs.devenv:8080", "request_id": "ce2ea835-e919-4c97-8f93-695009de2ff2", "method": "GetObjectACL", "bucket": "22ecd326-1189-4777-a664-df977db6b8be", "object": "572ee614-83be-49f3-b14e-fe3b44405eb8", "description": "OK"}
2023-07-17T03:30:14.394Z    s3  warn	handler/acl.go:344	====== GetObjectACLHandler, retry 0	{"encodeedObjectACL": {"Owner":{"ID":"NVbGSZ5WjhzwG8AGPkYqyXgm9yXvF915nH","DisplayName":"NVbGSZ5WjhzwG8AGPkYqyXgm9yXvF915nH"},"AccessControlList":[{"Grantee":{"DisplayName":"","EmailAddress":"","ID":"033b4387540dd267f4f7fb92a5acf5c83498ccefed57f0e36c15dd0ade3fbc8e7e","Type":"CanonicalUser","URI":""},"Permission":"FULL_CONTROL"},{"Grantee":{"DisplayName":"","EmailAddress":"","ID":"03681df6094fa48659a364db09019a0e07d5c753f2c37db5f49f21219ec445876f","Type":"CanonicalUser","URI":""},"Permission":"FULL_CONTROL"}]}}
2023-07-17T03:30:14.394Z    s3  warn	handler/acl.go:349	GetObjectACLHandler	{"================================= success =================================": {"Owner":{"ID":"NVbGSZ5WjhzwG8AGPkYqyXgm9yXvF915nH","DisplayName":"NVbGSZ5WjhzwG8AGPkYqyXgm9yXvF915nH"},"AccessControlList":[{"Grantee":{"DisplayName":"","EmailAddress":"","ID":"033b4387540dd267f4f7fb92a5acf5c83498ccefed57f0e36c15dd0ade3fbc8e7e","Type":"CanonicalUser","URI":""},"Permission":"FULL_CONTROL"},{"Grantee":{"DisplayName":"","EmailAddress":"","ID":"03681df6094fa48659a364db09019a0e07d5c753f2c37db5f49f21219ec445876f","Type":"CanonicalUser","URI":""},"Permission":"FULL_CONTROL"}]}}
2023-07-17T03:30:14.398Z    s3  debug	layer/layer.go:499	get object	{"reqId": "a96e51e0-20d8-4afb-be45-a8ec2955bfb4", "bucket": "22ecd326-1189-4777-a664-df977db6b8be", "cid": "B8QzYg9CxHQcN3Tmr7YnrELzNd4bJyoxbs2V3sNhWeQy", "object": "572ee614-83be-49f3-b14e-fe3b44405eb8", "oid": "262VzmpRy6E2B8UNTJjYaNVuefrPaQf5Cdddjwtd4qj9"}
2023-07-17T03:30:14.404Z    s3  info	api/router.go:162	call method	{"status": 200, "host": "s3.neofs.devenv:8080", "request_id": "a96e51e0-20d8-4afb-be45-a8ec2955bfb4", "method": "GetObject", "bucket": "22ecd326-1189-4777-a664-df977db6b8be", "object": "572ee614-83be-49f3-b14e-fe3b44405eb8", "description": "OK"}
```
> Logs with `======` is a locally debug extended logs and not represented in release/master versions of S3.

From this log, we see following picture:
* S3 correctly saves eACL data
* Sometimes S3 gate receives `null` in `AccessControlList` on _GetObjectACLHandler_. This is a result of using the pool inside S3 gate. Actually, it uses 4 nodes in a random way.
* If we get an empty eACL and wait one more second (logs with `====== GetObjectACLHandler,`), we receive the correct eACL.
* This fact is a result of syncing data between nodes and we read actual data. The second option is the transaction wasn't included in a block.

**Comment by roman-khimov** [comment] 2023-08-15 19:30
@smallhive, is it fixed now? Looks like.

**Comment by smallhive** [comment] 2023-08-16 04:23
I agree that it is fixed now. In the latest test runs S3 tests are green

**Closed** 2023-08-16 06:01 UTC
Labels: bug
